version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  node:
    depends_on:
      - mysqldb
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node_app
    restart: unless-stopped
    env_file: ./.env
    command: /usr/src/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./node/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
  vite_react:
    stdin_open: true
    container_name: vite_react_app
    build:
      context: ./vite-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./vite-react:/usr/src/app"
      - "/usr/src/app/node_modules"
    depends_on:
      - node
volumes:
  db: